version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db_prod
    restart: always
    environment:
      MYSQL_DATABASE: myproject
      MYSQL_USER: django_user
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data_prod:/var/lib/mysql
    networks:
      - mynetwork_prod
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build:
      context: ./backend/myproject
      dockerfile: Dockerfile.prod
    container_name: django_backend_prod
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DATABASE_URL=mysql://django_user:${DB_PASSWORD}@db:3306/myproject
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - FRONTEND_URL=${FRONTEND_URL}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - db
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    networks:
      - mynetwork_prod

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular_frontend_prod
    restart: always
    volumes:
      - frontend_build:/var/www/html
    networks:
      - mynetwork_prod

  nginx:
    image: nginx:alpine
    container_name: nginx_prod
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/www/static
      - media_volume:/var/www/media
      - frontend_build:/var/www/html
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - mynetwork_prod

volumes:
  mysql_data_prod:
  static_volume:
  media_volume:
  frontend_build:

networks:
  mynetwork_prod:
    driver: bridge
